version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: fraud_detection_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fraud_detection_network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: fraud_detection_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - fraud_detection_network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: fraud_detection_zookeeper
    ports:
      - "2181:2181"
    networks:
      - fraud_detection_network

volumes:
  mongo_data:

networks:
  fraud_detection_network: